<template>
  <div class="container">
    <el-card class="tool-card">
      <div class="table-wrap">
        <el-table
          :data="mimeTypes"
          stripe
          height="100%"
          class="mime-table"
        >
          <el-table-column
            class-name="col-ext"
            prop="extension"
            :label="$t('tools.mimeType.extension')"
            min-width="80"
          />
          <el-table-column
            class-name="col-mime"
            prop="mimeType"
            :label="$t('tools.mimeType.mimeType')"
            min-width="120"
          >
            <template #default="{ row }">
              <span class="copyable" :title="$t('common.copy')" @click="copyMime(row.mimeType)">
                <el-icon class="copy-icon"><CopyDocument /></el-icon>
                {{ row.mimeType }}
              </span>
            </template>
          </el-table-column>
        </el-table>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { CopyDocument } from '@element-plus/icons-vue'
import { copyToClipboard } from '@/utils'

const { t } = useI18n()

// 点击 Content-Type(Mime-Type) 列内容自动复制
const copyMime = (text) => {
  copyToClipboard(text, t('common.copied'))
}

const mimeTypes = [
  { extension: ".*（ 二进制流，不知道下载文件类型）", mimeType: "application/octet-stream" },
  { extension: ".001", mimeType: "application/x-001" },
  { extension: ".323", mimeType: "text/h323" },
  { extension: ".907", mimeType: "drawing/907" },
  { extension: ".acp", mimeType: "audio/x-mei-aac" },
  { extension: ".aif", mimeType: "audio/aiff" },
  { extension: ".aiff", mimeType: "audio/aiff" },
  { extension: ".asa", mimeType: "text/asa" },
  { extension: ".asp", mimeType: "text/asp" },
  { extension: ".au", mimeType: "audio/basic" },
  { extension: ".awf", mimeType: "application/vnd.adobe.workflow" },
  { extension: ".bmp", mimeType: "application/x-bmp" },
  { extension: ".c4t", mimeType: "application/x-c4t" },
  { extension: ".cal", mimeType: "application/x-cals" },
  { extension: ".cdf", mimeType: "application/x-netcdf" },
  { extension: ".cel", mimeType: "application/x-cel" },
  { extension: ".cg4", mimeType: "application/x-g4" },
  { extension: ".cit", mimeType: "application/x-cit" },
  { extension: ".cml", mimeType: "text/xml" },
  { extension: ".cmx", mimeType: "application/x-cmx" },
  { extension: ".crl", mimeType: "application/pkix-crl" },
  { extension: ".csi", mimeType: "application/x-csi" },
  { extension: ".cut", mimeType: "application/x-cut" },
  { extension: ".dbm", mimeType: "application/x-dbm" },
  { extension: ".dcd", mimeType: "text/xml" },
  { extension: ".der", mimeType: "application/x-x509-ca-cert" },
  { extension: ".dib", mimeType: "application/x-dib" },
  { extension: ".doc", mimeType: "application/msword" },
  { extension: ".drw", mimeType: "application/x-drw" },
  { extension: ".dwf", mimeType: "Model/vnd.dwf" },
  { extension: ".dwg", mimeType: "application/x-dwg" },
  { extension: ".dxf", mimeType: "application/x-dxf" },
  { extension: ".emf", mimeType: "application/x-emf" },
  { extension: ".ent", mimeType: "text/xml" },
  { extension: ".eps", mimeType: "application/x-ps" },
  { extension: ".etd", mimeType: "application/x-ebx" },
  { extension: ".fax", mimeType: "image/fax" },
  { extension: ".fif", mimeType: "application/fractals" },
  { extension: ".frm", mimeType: "application/x-frm" },
  { extension: ".gbr", mimeType: "application/x-gbr" },
  { extension: ".gif", mimeType: "image/gif" },
  { extension: ".gp4", mimeType: "application/x-gp4" },
  { extension: ".hmr", mimeType: "application/x-hmr" },
  { extension: ".hpl", mimeType: "application/x-hpl" },
  { extension: ".hrf", mimeType: "application/x-hrf" },
  { extension: ".htc", mimeType: "text/x-component" },
  { extension: ".html", mimeType: "text/html" },
  { extension: ".htx", mimeType: "text/html" },
  { extension: ".ico", mimeType: "image/x-icon" },
  { extension: ".iff", mimeType: "application/x-iff" },
  { extension: ".igs", mimeType: "application/x-igs" },
  { extension: ".img", mimeType: "application/x-img" },
  { extension: ".isp", mimeType: "application/x-internet-signup" },
  { extension: ".java", mimeType: "java/*" },
  { extension: ".jpe", mimeType: "image/jpeg" },
  { extension: ".jpeg", mimeType: "image/jpeg" },
  { extension: ".jpg", mimeType: "application/x-jpg" },
  { extension: ".jsp", mimeType: "text/html" },
  { extension: ".lar", mimeType: "application/x-laplayer-reg" },
  { extension: ".lavs", mimeType: "audio/x-liquid-secure" },
  { extension: ".lmsff", mimeType: "audio/x-la-lms" },
  { extension: ".ltr", mimeType: "application/x-ltr" },
  { extension: ".m2v", mimeType: "video/x-mpeg" },
  { extension: ".m4e", mimeType: "video/mpeg4" },
  { extension: ".man", mimeType: "application/x-troff-man" },
  { extension: ".mdb", mimeType: "application/msaccess" },
  { extension: ".mfp", mimeType: "application/x-shockwave-flash" },
  { extension: ".mhtml", mimeType: "message/rfc822" },
  { extension: ".mid", mimeType: "audio/mid" },
  { extension: ".mil", mimeType: "application/x-mil" },
  { extension: ".mnd", mimeType: "audio/x-musicnet-download" },
  { extension: ".mocha", mimeType: "application/x-javascript" },
  { extension: ".mp1", mimeType: "audio/mp1" },
  { extension: ".mp2v", mimeType: "video/mpeg" },
  { extension: ".mp4", mimeType: "video/mpeg4" },
  { extension: ".mpd", mimeType: "application/vnd.ms-project" },
  { extension: ".mpeg", mimeType: "video/mpg" },
  { extension: ".mpga", mimeType: "audio/rn-mpeg" },
  { extension: ".mps", mimeType: "video/x-mpeg" },
  { extension: ".mpv", mimeType: "video/mpg" },
  { extension: ".mpw", mimeType: "application/vnd.ms-project" },
  { extension: ".mtx", mimeType: "text/xml" },
  { extension: ".net", mimeType: "image/pnetvue" },
  { extension: ".nws", mimeType: "message/rfc822" },
  { extension: ".out", mimeType: "application/x-out" },
  { extension: ".p12", mimeType: "application/x-pkcs12" },
  { extension: ".p7c", mimeType: "application/pkcs7-mime" },
  { extension: ".p7r", mimeType: "application/x-pkcs7-certreqresp" },
  { extension: ".pc5", mimeType: "application/x-pc5" },
  { extension: ".pcl", mimeType: "application/x-pcl" },
  { extension: ".pdf", mimeType: "application/pdf" },
  { extension: ".pdx", mimeType: "application/vnd.adobe.pdx" },
  { extension: ".pgl", mimeType: "application/x-pgl" },
  { extension: ".pko", mimeType: "application/vnd.ms-pki.pko" },
  { extension: ".plg", mimeType: "text/html" },
  { extension: ".plt", mimeType: "application/x-plt" },
  { extension: ".png", mimeType: "application/x-png" },
  { extension: ".ppa", mimeType: "application/vnd.ms-powerpoint" },
  { extension: ".pps", mimeType: "application/vnd.ms-powerpoint" },
  { extension: ".ppt", mimeType: "application/x-ppt" },
  { extension: ".prf", mimeType: "application/pics-rules" },
  { extension: ".prt", mimeType: "application/x-prt" },
  { extension: ".ps", mimeType: "application/postscript" },
  { extension: ".pwz", mimeType: "application/vnd.ms-powerpoint" },
  { extension: ".ra", mimeType: "audio/vnd.rn-realaudio" },
  { extension: ".ras", mimeType: "application/x-ras" },
  { extension: ".rdf", mimeType: "text/xml" },
  { extension: ".red", mimeType: "application/x-red" },
  { extension: ".rjs", mimeType: "application/vnd.rn-realsystem-rjs" },
  { extension: ".rlc", mimeType: "application/x-rlc" },
  { extension: ".rm", mimeType: "application/vnd.rn-realmedia" },
  { extension: ".rmi", mimeType: "audio/mid" },
  { extension: ".rmm", mimeType: "audio/x-pn-realaudio" },
  { extension: ".rms", mimeType: "application/vnd.rn-realmedia-secure" },
  { extension: ".rmx", mimeType: "application/vnd.rn-realsystem-rmx" },
  { extension: ".rp", mimeType: "image/vnd.rn-realpix" },
  { extension: ".rsml", mimeType: "application/vnd.rn-rsml" },
  { extension: ".rtf", mimeType: "application/msword" },
  { extension: ".rv", mimeType: "video/vnd.rn-realvideo" },
  { extension: ".sat", mimeType: "application/x-sat" },
  { extension: ".sdw", mimeType: "application/x-sdw" },
  { extension: ".slb", mimeType: "application/x-slb" },
  { extension: ".slk", mimeType: "drawing/x-slk" },
  { extension: ".smil", mimeType: "application/smil" },
  { extension: ".snd", mimeType: "audio/basic" },
  { extension: ".sor", mimeType: "text/plain" },
  { extension: ".spl", mimeType: "application/futuresplash" },
  { extension: ".ssm", mimeType: "application/streamingmedia" },
  { extension: ".stl", mimeType: "application/vnd.ms-pki.stl" },
  { extension: ".sty", mimeType: "application/x-sty" },
  { extension: ".swf", mimeType: "application/x-shockwave-flash" },
  { extension: ".tg4", mimeType: "application/x-tg4" },
  { extension: ".tif", mimeType: "image/tiff" },
  { extension: ".tiff", mimeType: "image/tiff" },
  { extension: ".top", mimeType: "drawing/x-top" },
  { extension: ".tsd", mimeType: "text/xml" },
  { extension: ".uin", mimeType: "application/x-icq" },
  { extension: ".vcf", mimeType: "text/x-vcard" },
  { extension: ".vdx", mimeType: "application/vnd.visio" },
  { extension: ".vpg", mimeType: "application/x-vpeg005" },
  { extension: ".vsd", mimeType: "application/x-vsd" },
  { extension: ".vst", mimeType: "application/vnd.visio" },
  { extension: ".vsw", mimeType: "application/vnd.visio" },
  { extension: ".vtx", mimeType: "application/vnd.visio" },
  { extension: ".wav", mimeType: "audio/wav" },
  { extension: ".wb1", mimeType: "application/x-wb1" },
  { extension: ".wb3", mimeType: "application/x-wb3" },
  { extension: ".wiz", mimeType: "application/msword" },
  { extension: ".wk4", mimeType: "application/x-wk4" },
  { extension: ".wks", mimeType: "application/x-wks" },
  { extension: ".wma", mimeType: "audio/x-ms-wma" },
  { extension: ".wmf", mimeType: "application/x-wmf" },
  { extension: ".wmv", mimeType: "video/x-ms-wmv" },
  { extension: ".wmz", mimeType: "application/x-ms-wmz" },
  { extension: ".wpd", mimeType: "application/x-wpd" },
  { extension: ".wpl", mimeType: "application/vnd.ms-wpl" },
  { extension: ".wr1", mimeType: "application/x-wr1" },
  { extension: ".wrk", mimeType: "application/x-wrk" },
  { extension: ".ws2", mimeType: "application/x-ws" },
  { extension: ".wsdl", mimeType: "text/xml" },
  { extension: ".xdp", mimeType: "application/vnd.adobe.xdp" },
  { extension: ".xfd", mimeType: "application/vnd.adobe.xfd" },
  { extension: ".xhtml", mimeType: "text/html" },
  { extension: ".xls", mimeType: "application/x-xls" },
  { extension: ".xml", mimeType: "text/xml" },
  { extension: ".xq", mimeType: "text/xml" },
  { extension: ".xquery", mimeType: "text/xml" },
  { extension: ".xsl", mimeType: "text/xml" },
  { extension: ".xwd", mimeType: "application/x-xwd" },
  { extension: ".sis", mimeType: "application/vnd.symbian.install" },
  { extension: ".x_t", mimeType: "application/x-x_t" },
  { extension: ".apk", mimeType: "application/vnd.android.package-archive" },
  { extension: ".tif", mimeType: "image/tiff" },
  { extension: ".301", mimeType: "application/x-301" },
  { extension: ".906", mimeType: "application/x-906" },
  { extension: ".a11", mimeType: "application/x-a11" },
  { extension: ".ai", mimeType: "application/postscript" },
  { extension: ".aifc", mimeType: "audio/aiff" },
  { extension: ".anv", mimeType: "application/x-anv" },
  { extension: ".asf", mimeType: "video/x-ms-asf" },
  { extension: ".asx", mimeType: "video/x-ms-asf" },
  { extension: ".avi", mimeType: "video/avi" },
  { extension: ".biz", mimeType: "text/xml" },
  { extension: ".bot", mimeType: "application/x-bot" },
  { extension: ".c90", mimeType: "application/x-c90" },
  { extension: ".cat", mimeType: "application/vnd.ms-pki.seccat" },
  { extension: ".cdr", mimeType: "application/x-cdr" },
  { extension: ".cer", mimeType: "application/x-x509-ca-cert" },
  { extension: ".cgm", mimeType: "application/x-cgm" },
  { extension: ".class", mimeType: "java/*" },
  { extension: ".cmp", mimeType: "application/x-cmp" },
  { extension: ".cot", mimeType: "application/x-cot" },
  { extension: ".crt", mimeType: "application/x-x509-ca-cert" },
  { extension: ".css", mimeType: "text/css" },
  { extension: ".dbf", mimeType: "application/x-dbf" },
  { extension: ".dbx", mimeType: "application/x-dbx" },
  { extension: ".dcx", mimeType: "application/x-dcx" },
  { extension: ".dgn", mimeType: "application/x-dgn" },
  { extension: ".dll", mimeType: "application/x-msdownload" },
  { extension: ".dot", mimeType: "application/msword" },
  { extension: ".dtd", mimeType: "text/xml" },
  { extension: ".dwf", mimeType: "application/x-dwf" },
  { extension: ".dxb", mimeType: "application/x-dxb" },
  { extension: ".edn", mimeType: "application/vnd.adobe.edn" },
  { extension: ".eml", mimeType: "message/rfc822" },
  { extension: ".epi", mimeType: "application/x-epi" },
  { extension: ".eps", mimeType: "application/postscript" },
  { extension: ".exe", mimeType: "application/x-msdownload" },
  { extension: ".fdf", mimeType: "application/vnd.fdf" },
  { extension: ".fo", mimeType: "text/xml" },
  { extension: ".g4", mimeType: "application/x-g4" },
  { extension: ".", mimeType: "application/x-" },
  { extension: ".gl2", mimeType: "application/x-gl2" },
  { extension: ".hgl", mimeType: "application/x-hgl" },
  { extension: ".hpg", mimeType: "application/x-hpgl" },
  { extension: ".hqx", mimeType: "application/mac-binhex40" },
  { extension: ".hta", mimeType: "application/hta" },
  { extension: ".htm", mimeType: "text/html" },
  { extension: ".htt", mimeType: "text/webviewhtml" },
  { extension: ".icb", mimeType: "application/x-icb" },
  { extension: ".ico", mimeType: "application/x-ico" },
  { extension: ".ig4", mimeType: "application/x-g4" },
  { extension: ".iii", mimeType: "application/x-iphone" },
  { extension: ".ins", mimeType: "application/x-internet-signup" },
  { extension: ".IVF", mimeType: "video/x-ivf" },
  { extension: ".jfif", mimeType: "image/jpeg" },
  { extension: ".jpe", mimeType: "application/x-jpe" },
  { extension: ".jpg", mimeType: "image/jpeg" },
  { extension: ".js", mimeType: "application/x-javascript" },
  { extension: ".la1", mimeType: "audio/x-liquid-file" },
  { extension: ".latex", mimeType: "application/x-latex" },
  { extension: ".lbm", mimeType: "application/x-lbm" },
  { extension: ".ls", mimeType: "application/x-javascript" },
  { extension: ".m1v", mimeType: "video/x-mpeg" },
  { extension: ".m3u", mimeType: "audio/mpegurl" },
  { extension: ".mac", mimeType: "application/x-mac" },
  { extension: ".math", mimeType: "text/xml" },
  { extension: ".mdb", mimeType: "application/x-mdb" },
  { extension: ".mht", mimeType: "message/rfc822" },
  { extension: ".mi", mimeType: "application/x-mi" },
  { extension: ".midi", mimeType: "audio/mid" },
  { extension: ".mml", mimeType: "text/xml" },
  { extension: ".mns", mimeType: "audio/x-musicnet-stream" },
  { extension: ".movie", mimeType: "video/x-sgi-movie" },
  { extension: ".mp2", mimeType: "audio/mp2" },
  { extension: ".mp3", mimeType: "audio/mp3" },
  { extension: ".mpa", mimeType: "video/x-mpg" },
  { extension: ".mpe", mimeType: "video/x-mpeg" },
  { extension: ".mpg", mimeType: "video/mpg" },
  { extension: ".mpp", mimeType: "application/vnd.ms-project" },
  { extension: ".mpt", mimeType: "application/vnd.ms-project" },
  { extension: ".mpv2", mimeType: "video/mpeg" },
  { extension: ".mpx", mimeType: "application/vnd.ms-project" },
  { extension: ".mxp", mimeType: "application/x-mmxp" },
  { extension: ".nrf", mimeType: "application/x-nrf" },
  { extension: ".odc", mimeType: "text/x-ms-odc" },
  { extension: ".p10", mimeType: "application/pkcs10" },
  { extension: ".p7b", mimeType: "application/x-pkcs7-certificates" },
  { extension: ".p7m", mimeType: "application/pkcs7-mime" },
  { extension: ".p7s", mimeType: "application/pkcs7-signature" },
  { extension: ".pci", mimeType: "application/x-pci" },
  { extension: ".pcx", mimeType: "application/x-pcx" },
  { extension: ".pdf", mimeType: "application/pdf" },
  { extension: ".pfx", mimeType: "application/x-pkcs12" },
  { extension: ".pic", mimeType: "application/x-pic" },
  { extension: ".pl", mimeType: "application/x-perl" },
  { extension: ".pls", mimeType: "audio/scpls" },
  { extension: ".png", mimeType: "image/png" },
  { extension: ".pot", mimeType: "application/vnd.ms-powerpoint" },
  { extension: ".ppm", mimeType: "application/x-ppm" },
  { extension: ".ppt", mimeType: "application/vnd.ms-powerpoint" },
  { extension: ".pr", mimeType: "application/x-pr" },
  { extension: ".prn", mimeType: "application/x-prn" },
  { extension: ".ps", mimeType: "application/x-ps" },
  { extension: ".ptn", mimeType: "application/x-ptn" },
  { extension: ".r3t", mimeType: "text/vnd.rn-realtext3d" },
  { extension: ".ram", mimeType: "audio/x-pn-realaudio" },
  { extension: ".rat", mimeType: "application/rat-file" },
  { extension: ".rec", mimeType: "application/vnd.rn-recording" },
  { extension: ".rgb", mimeType: "application/x-rgb" },
  { extension: ".rjt", mimeType: "application/vnd.rn-realsystem-rjt" },
  { extension: ".rle", mimeType: "application/x-rle" },
  { extension: ".rmf", mimeType: "application/vnd.adobe.rmf" },
  { extension: ".rmj", mimeType: "application/vnd.rn-realsystem-rmj" },
  { extension: ".rmp", mimeType: "application/vnd.rn-rn_music_package" },
  { extension: ".rmvb", mimeType: "application/vnd.rn-realmedia-vbr" },
  { extension: ".rnx", mimeType: "application/vnd.rn-realplayer" },
  { extension: ".rpm", mimeType: "audio/x-pn-realaudio-plugin" },
  { extension: ".rt", mimeType: "text/vnd.rn-realtext" },
  { extension: ".rtf", mimeType: "application/x-rtf" },
  { extension: ".sam", mimeType: "application/x-sam" },
  { extension: ".sdp", mimeType: "application/sdp" },
  { extension: ".sit", mimeType: "application/x-stuffit" },
  { extension: ".sld", mimeType: "application/x-sld" },
  { extension: ".smi", mimeType: "application/smil" },
  { extension: ".smk", mimeType: "application/x-smk" },
  { extension: ".sol", mimeType: "text/plain" },
  { extension: ".spc", mimeType: "application/x-pkcs7-certificates" },
  { extension: ".spp", mimeType: "text/xml" },
  { extension: ".sst", mimeType: "application/vnd.ms-pki.certstore" },
  { extension: ".stm", mimeType: "text/html" },
  { extension: ".svg", mimeType: "text/xml" },
  { extension: ".tdf", mimeType: "application/x-tdf" },
  { extension: ".tga", mimeType: "application/x-tga" },
  { extension: ".tif", mimeType: "application/x-tif" },
  { extension: ".tld", mimeType: "text/xml" },
  { extension: ".torrent", mimeType: "application/x-bittorrent" },
  { extension: ".txt", mimeType: "text/plain" },
  { extension: ".uls", mimeType: "text/iuls" },
  { extension: ".vda", mimeType: "application/x-vda" },
  { extension: ".vml", mimeType: "text/xml" },
  { extension: ".vsd", mimeType: "application/vnd.visio" },
  { extension: ".vss", mimeType: "application/vnd.visio" },
  { extension: ".vst", mimeType: "application/x-vst" },
  { extension: ".vsx", mimeType: "application/vnd.visio" },
  { extension: ".vxml", mimeType: "text/xml" },
  { extension: ".wax", mimeType: "audio/x-ms-wax" },
  { extension: ".wb2", mimeType: "application/x-wb2" },
  { extension: ".wbmp", mimeType: "image/vnd.wap.wbmp" },
  { extension: ".wk3", mimeType: "application/x-wk3" },
  { extension: ".wkq", mimeType: "application/x-wkq" },
  { extension: ".wm", mimeType: "video/x-ms-wm" },
  { extension: ".wmd", mimeType: "application/x-ms-wmd" },
  { extension: ".wml", mimeType: "text/vnd.wap.wml" },
  { extension: ".wmx", mimeType: "video/x-ms-wmx" },
  { extension: ".wp6", mimeType: "application/x-wp6" },
  { extension: ".wpg", mimeType: "application/x-wpg" },
  { extension: ".wq1", mimeType: "application/x-wq1" },
  { extension: ".wri", mimeType: "application/x-wri" },
  { extension: ".ws", mimeType: "application/x-ws" },
  { extension: ".wsc", mimeType: "text/scriptlet" },
  { extension: ".wvx", mimeType: "video/x-ms-wvx" },
  { extension: ".xdr", mimeType: "text/xml" },
  { extension: ".xfdf", mimeType: "application/vnd.adobe.xfdf" },
  { extension: ".xls", mimeType: "application/vnd.ms-excel" },
  { extension: ".xlw", mimeType: "application/x-xlw" },
  { extension: ".xpl", mimeType: "audio/scpls" },
  { extension: ".xql", mimeType: "text/xml" },
  { extension: ".xsd", mimeType: "text/xml" },
  { extension: ".xslt", mimeType: "text/xml" },
  { extension: ".x_b", mimeType: "application/x-x_b" },
  { extension: ".sisx", mimeType: "application/vnd.symbian.install" },
  { extension: ".ipa", mimeType: "application/vnd.iphone" },
  { extension: ".xap", mimeType: "application/x-silverlight-app" },
]
</script>

<style scoped lang="scss">
// H5 模式：两列各占 50%（覆盖 Element Plus 计算的 40/60 比例列宽）
@media (max-width: 768px) {
  :deep(.mime-table) {
    .el-table__header colgroup col,
    .el-table__body colgroup col,
    .el-table__header th.col-ext,
    .el-table__header th.col-mime,
    .el-table__body td.col-ext,
    .el-table__body td.col-mime {
      width: 50% !important;
    }
  }
}
</style>
